user_name: Hugo
communication_language: Francais
document_output_language: Francais
output_folder: '{project-root}/_bmad-output'
installed_by: yanstaller
installed_at: '2026-02-11T07:43:54.967Z'
version: 1.2.0
mode: custom
agents_installed:
  - byan
  - rachid
  - party-mode
  - marc
  - patnote
  - kurdant-react-dev
  - kurdant-ux-ui
bmb_creations_output_folder: '{project-root}/_bmad-output/bmb-creations'
